# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters

run:
  issues-exit-code: 1

issues:
  max-same-issues: 0

version: "2"

linters-settings:
  misspell:
    locale: US
# above for testing
linters:
  enable:
    - durationcheck
    - errcheck
    - exportloopref
    - forcetypeassert
    - godot
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused
    - vet