data "jamfpro_mobile_device_configuration_profile" "jamfpro_mobile_device_configuration_profile_001_data" {
  id = jamfpro_mobile_device_configuration_profile.jamfpro_mobile_device_configuration_profile_001.id
}

output "jamfpro_mobile_device_configuration_profile_001_data_id" {
  value = data.jamfpro_mobile_device_configuration_profile.jamfpro_mobile_device_configuration_profile_001_data.id
}

output "jamfpro_mobile_device_configuration_profile_001_data_name" {
  value = data.jamfpro_mobile_device_configuration_profile.jamfpro_mobile_device_configuration_profile_001_data.name
}