// apiroles_data_validation.go
package apiroles

import (
	"fmt"
	"sort"
	"strings"
)

// TODO review this whole file

// List of valid privileges - replace these with actual valid privileges.
var validPrivileges = []string{
	"Create Custom Paths",
	"Read Custom Paths",
	"Update Custom Paths",
	"Delete Custom Paths",
	"Create API Integrations",
	"Read API Integrations",
	"Update API Integrations",
	"Delete API Integrations",
	"Create API Roles",
	"Read API Roles",
	"Update API Roles",
	"Delete API Roles",
	"Create Self Service Branding Configuration",
	"Read Self Service Branding Configuration",
	"Update Self Service Branding Configuration",
	"Delete Self Service Branding Configuration",
	"Create Jamf Content Distribution Server Files",
	"Read Jamf Content Distribution Server Files",
	"Delete Jamf Content Distribution Server Files",
	"Create Remote Administration",
	"Read Remote Administration",
	"Update Remote Administration",
	"Delete Remote Administration",
	"Create Managed Software Updates",
	"Read Managed Software Updates",
	"Update Managed Software Updates",
	"Delete Managed Software Updates",
	"Create Jamf Protect Deployments",
	"Read Jamf Protect Deployments",
	"Update Jamf Protect Deployments",
	"Delete Jamf Protect Deployments",
	"Create Jamf Connect Deployments",
	"Read Jamf Connect Deployments",
	"Update Jamf Connect Deployments",
	"Delete Jamf Connect Deployments",
	"Create Categories",
	"Read Categories",
	"Update Categories",
	"Delete Categories",
	"Create Licensed Software",
	"Read Licensed Software",
	"Update Licensed Software",
	"Delete Licensed Software",
	"Create Volume Purchasing Locations",
	"Read Volume Purchasing Locations",
	"Update Volume Purchasing Locations",
	"Delete Volume Purchasing Locations",
	"Create Computers",
	"Read Computers",
	"Update Computers",
	"Delete Computers",
	"Create Packages",
	"Read Packages",
	"Update Packages",
	"Delete Packages",
	"Create Disk Encryption Configurations",
	"Read Disk Encryption Configurations",
	"Update Disk Encryption Configurations",
	"Delete Disk Encryption Configurations",
	"Create Smart Computer Groups",
	"Read Smart Computer Groups",
	"Update Smart Computer Groups",
	"Delete Smart Computer Groups",
	"Create Smart Mobile Device Groups",
	"Read Smart Mobile Device Groups",
	"Update Smart Mobile Device Groups",
	"Delete Smart Mobile Device Groups",
	"Create Device Enrollment Program Instances",
	"Read Device Enrollment Program Instances",
	"Update Device Enrollment Program Instances",
	"Delete Device Enrollment Program Instances",
	"Create Network Segments",
	"Read Network Segments",
	"Update Network Segments",
	"Delete Network Segments",
	"Create Attachment Assignments",
	"Read Attachment Assignments",
	"Update Attachment Assignments",
	"Delete Attachment Assignments",
	"Create Mobile Device PreStage Enrollments",
	"Read Mobile Device PreStage Enrollments",
	"Update Mobile Device PreStage Enrollments",
	"Delete Mobile Device PreStage Enrollments",
	"Create Smart User Groups",
	"Read Smart User Groups",
	"Update Smart User Groups",
	"Delete Smart User Groups",
	"Create User",
	"Read User",
	"Update User",
	"Delete User",
	"Create Dock Items",
	"Read Dock Items",
	"Update Dock Items",
	"Delete Dock Items",
	"Create Departments",
	"Read Departments",
	"Update Departments",
	"Delete Departments",
	"Create Push Certificates",
	"Read Push Certificates",
	"Update Push Certificates",
	"Delete Push Certificates",
	"Create File Attachments",
	"Read File Attachments",
	"Update File Attachments",
	"Delete File Attachments",
	"Create VPP Invitations",
	"Read VPP Invitations",
	"Update VPP Invitations",
	"Delete VPP Invitations",
	"Create Mobile Device Managed App Configurations",
	"Read Mobile Device Managed App Configurations",
	"Update Mobile Device Managed App Configurations",
	"Delete Mobile Device Managed App Configurations",
	"Create Infrastructure Managers",
	"Read Infrastructure Managers",
	"Update Infrastructure Managers",
	"Delete Infrastructure Managers",
	"Create Webhooks",
	"Read Webhooks",
	"Update Webhooks",
	"Delete Webhooks",
	"Create Buildings",
	"Read Buildings",
	"Update Buildings",
	"Delete Buildings",
	"Create Enrollment Profiles",
	"Read Enrollment Profiles",
	"Update Enrollment Profiles",
	"Delete Enrollment Profiles",
	"Create iOS Configuration Profiles",
	"Read iOS Configuration Profiles",
	"Update iOS Configuration Profiles",
	"Delete iOS Configuration Profiles",
	"Create AirPlay Permissions",
	"Read AirPlay Permissions",
	"Update AirPlay Permissions",
	"Delete AirPlay Permissions",
	"Create Advanced User Searches",
	"Read Advanced User Searches",
	"Update Advanced User Searches",
	"Delete Advanced User Searches",
	"Create LDAP Servers",
	"Read LDAP Servers",
	"Update LDAP Servers",
	"Delete LDAP Servers",
	"Create Mobile Devices",
	"Read Mobile Devices",
	"Update Mobile Devices",
	"Delete Mobile Devices",
	"Create Software Update Servers",
	"Read Software Update Servers",
	"Update Software Update Servers",
	"Delete Software Update Servers",
	"Create Sites",
	"Read Sites",
	"Update Sites",
	"Delete Sites",
	"Create Policies",
	"Read Policies",
	"Update Policies",
	"Delete Policies",
	"Create Computer Extension Attributes",
	"Read Computer Extension Attributes",
	"Update Computer Extension Attributes",
	"Delete Computer Extension Attributes",
	"Create JSON Web Token Configuration",
	"Read JSON Web Token Configuration",
	"Update JSON Web Token Configuration",
	"Delete JSON Web Token Configuration",
	"Create Printers",
	"Read Printers",
	"Update Printers",
	"Delete Printers",
	"Create Inventory Preload Records",
	"Read Inventory Preload Records",
	"Update Inventory Preload Records",
	"Delete Inventory Preload Records",
	"Create Patch External Source",
	"Read Patch External Source",
	"Update Patch External Source",
	"Delete Patch External Source",
	"Create eBooks",
	"Read eBooks",
	"Update eBooks",
	"Delete eBooks",
	"Create Restricted Software",
	"Read Restricted Software",
	"Update Restricted Software",
	"Delete Restricted Software",
	"Create Peripheral Types",
	"Read Peripheral Types",
	"Update Peripheral Types",
	"Delete Peripheral Types",
	"Create Scripts",
	"Read Scripts",
	"Update Scripts",
	"Delete Scripts",
	"Create iBeacon",
	"Read iBeacon",
	"Update iBeacon",
	"Delete iBeacon",
	"Create Computer PreStage Enrollments",
	"Read Computer PreStage Enrollments",
	"Update Computer PreStage Enrollments",
	"Delete Computer PreStage Enrollments",
	"Create Mobile Device Extension Attributes",
	"Read Mobile Device Extension Attributes",
	"Update Mobile Device Extension Attributes",
	"Delete Mobile Device Extension Attributes",
	"Create Directory Bindings",
	"Read Directory Bindings",
	"Update Directory Bindings",
	"Delete Directory Bindings",
	"Create macOS Configuration Profiles",
	"Read macOS Configuration Profiles",
	"Update macOS Configuration Profiles",
	"Delete macOS Configuration Profiles",
	"Create Patch Management Software Titles",
	"Read Patch Management Software Titles",
	"Update Patch Management Software Titles",
	"Delete Patch Management Software Titles",
	"Create Device Name Patterns",
	"Read Device Name Patterns",
	"Update Device Name Patterns",
	"Delete Device Name Patterns",
	"Create Distribution Points",
	"Read Distribution Points",
	"Update Distribution Points",
	"Delete Distribution Points",
	"Create Disk Encryption Institutional Configurations",
	"Read Disk Encryption Institutional Configurations",
	"Update Disk Encryption Institutional Configurations",
	"Delete Disk Encryption Institutional Configurations",
	"Create Patch Policies",
	"Read Patch Policies",
	"Update Patch Policies",
	"Delete Patch Policies",
	"Create Mobile Device Enrollment Invitations",
	"Read Mobile Device Enrollment Invitations",
	"Update Mobile Device Enrollment Invitations",
	"Delete Mobile Device Enrollment Invitations",
	"Create Advanced Mobile Device Searches",
	"Read Advanced Mobile Device Searches",
	"Update Advanced Mobile Device Searches",
	"Delete Advanced Mobile Device Searches",
	"Create Static Mobile Device Groups",
	"Read Static Mobile Device Groups",
	"Update Static Mobile Device Groups",
	"Delete Static Mobile Device Groups",
	"Create VPP Assignment",
	"Read VPP Assignment",
	"Update VPP Assignment",
	"Delete VPP Assignment",
	"Create Static User Groups",
	"Read Static User Groups",
	"Update Static User Groups",
	"Delete Static User Groups",
	"Create Network Integration",
	"Read Network Integration",
	"Update Network Integration",
	"Delete Network Integration",
	"Create Enrollment Customizations",
	"Read Enrollment Customizations",
	"Update Enrollment Customizations",
	"Delete Enrollment Customizations",
	"Create Mac Applications",
	"Read Mac Applications",
	"Update Mac Applications",
	"Delete Mac Applications",
	"Create Allowed File Extension",
	"Read Allowed File Extension",
	"Delete Allowed File Extension",
	"Create Accounts",
	"Read Accounts",
	"Update Accounts",
	"Delete Accounts",
	"Create Provisioning Profiles",
	"Read Provisioning Profiles",
	"Update Provisioning Profiles",
	"Delete Provisioning Profiles",
	"Create Removable MAC Address",
	"Read Removable MAC Address",
	"Update Removable MAC Address",
	"Delete Removable MAC Address",
	"Create Personal Device Configurations",
	"Read Personal Device Configurations",
	"Update Personal Device Configurations",
	"Delete Personal Device Configurations",
	"Create Self Service Bookmarks",
	"Read Self Service Bookmarks",
	"Update Self Service Bookmarks",
	"Delete Self Service Bookmarks",
	"Create Personal Device Profiles",
	"Read Personal Device Profiles",
	"Update Personal Device Profiles",
	"Delete Personal Device Profiles",
	"Create Computer Enrollment Invitations",
	"Read Computer Enrollment Invitations",
	"Update Computer Enrollment Invitations",
	"Delete Computer Enrollment Invitations",
	"Create Keystore",
	"Read Keystores",
	"Update Keystores",
	"Delete Keystores",
	"Create Static Computer Groups",
	"Read Static Computer Groups",
	"Update Static Computer Groups",
	"Delete Static Computer Groups",
	"Create Advanced Computer Searches",
	"Read Advanced Computer Searches",
	"Update Advanced Computer Searches",
	"Delete Advanced Computer Searches",
	"Create Maintenance Pages",
	"Read Maintenance Pages",
	"Update Maintenance Pages",
	"Delete Maintenance Pages",
	"Create Advanced User Content Searches",
	"Read Advanced User Content Searches",
	"Update Advanced User Content Searches",
	"Delete Advanced User Content Searches",
	"Create Classes",
	"Read Classes",
	"Update Classes",
	"Delete Classes",
	"Create Mobile Device Applications",
	"Read Mobile Device Applications",
	"Update Mobile Device Applications",
	"Delete Mobile Device Applications",
	"Create User Extension Attributes",
	"Read User Extension Attributes",
	"Update User Extension Attributes",
	"Delete User Extension Attributes",
	"Jamf Connect Deployment Retry",
	"Remove restrictions set by Jamf Parent",
	"Remove Jamf Parent management capabilities",
	"CLEAR_TEACHER_PROFILE_PRIVILEGE",
	"Jamf Packages Action",
	"Send MDM Check In Command",
	"Jamf Protect Deployment Retry",
	"Allow User to Enroll",
	"Assign Users to Mobile Devices",
	"Assign Users to Computers",
	"Enroll Computers",
	"Enroll Mobile Devices",
	"Change Password",
	"View License Serial Numbers",
	"Send Email to End Users via JSS",
	"Send Computer Remote Lock Command",
	"Send Computer Remote Wipe Command",
	"Send Computer Unmanage Command",
	"Send Computer Unlock User Account Command",
	"Send Computer Delete User Account Command",
	"Send Computer Set Activation Lock Command",
	"View Disk Encryption Recovery Key",
	"View Activation Lock Bypass Code",
	"Flush Policy Logs",
	"Send Computer Remote Command to Download and Install OS X Update",
	"Send Computer Bluetooth Command",
	"Send Computer Remote Desktop Command",
	"Send Computer Remote Command to Install Package",
	"Send Set Recovery Lock Command",
	"View Recovery Lock",
	"Send Inventory Requests to Mobile Devices",
	"Send Mobile Device Remote Lock Command",
	"Send Mobile Device Remove Passcode Command",
	"Send Mobile Device Remove Restrictions Password Command",
	"Send Mobile Device Remote Wipe Command",
	"Send Mobile Device Set Activation Lock Command",
	"Unmanage Mobile Devices",
	"Send Mobile Device Managed Settings Command",
	"Send Mobile Device Mirroring Command",
	"Send Mobile Device Set Wallpaper Command",
	"Update watchOS Enrollment Settings",
	"Send Blank Pushes to Mobile Devices",
	"Send Mobile Device Enable Voice Roaming Command",
	"Send Mobile Device Disable Voice Roaming Command",
	"Send Mobile Device Enable Data Roaming Command",
	"Send Mobile Device Disable Data Roaming Command",
	"Send Mobile Device Set Device Name Command",
	"Send Mobile Device Remote Command to Download and Install iOS Update",
	"Send Mobile Device Lost Mode Command",
	"View Mobile Device Lost Mode Location",
	"Send Mobile Device Shared iPad Commands",
	"Send Mobile Device Diagnostics and Usage Reporting and App Analytics Commands",
	"Send Software Update Settings Command",
	"Send Mobile Device Restart Device Command",
	"View JSS Information",
	"Send Messages to Self Service Mobile",
	"View Event Logs",
	"Dismiss Notifications",
	"Send Update Passcode Lock Grace Period Command",
	"Send Mobile Device Shut Down Command",
	"Send Mobile Device Bluetooth Command",
	"Send Mobile Device Personal Hotspot Command",
	"Send Mobile Device Refresh Cellular Plans Command",
	"Send Command to Renew MDM Profile",
	"Send Declarative Management Command",
	"Flush MDM Commands",
	"Send Mobile Device Shared Device Configuration Commands",
	"Renewal of the Built-in Certificate Authority",
	"View MDM command information in Jamf Pro API",
	"Send Set Timezone Command",
	"Send Application Attributes Command",
	"Send Enable Bootstrap Token Command",
	"Send Disable Bootstrap Token Command",
	"Send Mobile Device Software Update Recommendation Cadence Command",
	"Update Local Admin Password Settings",
	"View Local Admin Password",
	"View Local Admin Password Audit History",
	"Send Local Admin Password Command",
	"Start Remote Assist Session",
	"Edit Return To Service Configurations",
	"View Return To Service Configurations",
	"Delete Return To Service Configurations",
	"Send Device Information Command",
	"Read SSO Settings",
	"Update SSO Settings",
	"Read Automatically Renew MDM Profile Settings",
	"Update Automatically Renew MDM Profile Settings",
	"Read Computer Inventory Collection Settings",
	"Update Computer Inventory Collection Settings",
	"Read Login Disclaimer",
	"Update Login Disclaimer",
	"Read Parent App Settings",
	"Update Parent App Settings",
	"Read Teacher App Settings",
	"Update Teacher App Settings",
	"Read Onboarding Configuration",
	"Update Onboarding Configuration",
	"Read Device Compliance Information",
	"Read Jamf Protect Settings",
	"Update Jamf Protect Settings",
	"Read Re-enrollment",
	"Update Re-enrollment",
	"Read App Request Settings",
	"Update App Request Settings",
	"Read Remote Assist",
	"Update Remote Assist",
	"Read Cloud Services Settings",
	"Update Cloud Services Settings",
	"Read Engage Settings",
	"Update Engage Settings",
	"Read Jamf Connect Settings",
	"Update Jamf Connect Settings",
	"Read Computer Check-In",
	"Update Computer Check-In",
	"Read Change Management",
	"Update Change Management",
	"Read Mobile Device Self Service",
	"Update Mobile Device Self Service",
	"Read SMTP Server",
	"Update SMTP Server",
	"Read PKI",
	"Update PKI",
	"Read Activation Code",
	"Update Activation Code",
	"Read Apache Tomcat Settings",
	"Update Apache Tomcat Settings",
	"Read Conditional Access",
	"Update Conditional Access",
	"Read Mobile Device Inventory Collection",
	"Update Mobile Device Inventory Collection",
	"Read Clustering",
	"Update Clustering",
	"Read Computer Inventory Collection",
	"Update Computer Inventory Collection",
	"Read Self Service",
	"Update Self Service",
	"Read Password Policy",
	"Update Password Policy",
	"Read Limited Access Settings",
	"Update Limited Access Settings",
	"Read Mobile Device App Maintenance Settings",
	"Update Mobile Device App Maintenance Settings",
	"Read Patch Internal Source",
	"Read User-Initiated Enrollment",
	"Update User-Initiated Enrollment",
	"Read Retention Policy",
	"Update Retention Policy",
	"Read Education Settings",
	"Update Education Settings",
	"Read GSX Connection",
	"Update GSX Connection",
	"Read Automatic Mac App Updates Settings",
	"Update Automatic Mac App Updates Settings",
	"Read Computer Check-In",
	"Update Computer Check-In",
	"Read JSS URL",
	"Update JSS URL",
	"Read Patch Management Settings",
	"Update Patch Management Settings",
	"Read Cache",
	"Update Cache",
	"Read Apple Configurator Enrollment",
	"Update Apple Configurator Enrollment",
	"Read Computer Security",
	"Update Computer Security",
	"Read Cloud Distribution Point",
	"Update Cloud Distribution Point",
}

// validateResourceApiRolesDataFields checks if a given privilege is in the list of valid privileges
// and groups privileges by category.
func validateResourceApiRolesDataFields(val interface{}, key string) (warns []string, errs []error) {
	v := val.(string)

	categories := make(map[string][]string)
	var nonCrudPrivileges []string
	var MDMCommands []string

	for _, priv := range validPrivileges {
		if v == priv {
			return
		}

		// Split the privilege into operation and category
		parts := strings.SplitN(priv, " ", 2)
		if len(parts) == 2 {
			operation, category := parts[0], parts[1]

			// Group CRUD privileges by category
			if operation == "Create" || operation == "Read" || operation == "Update" || operation == "Delete" {
				categories[category] = append(categories[category], priv)
			} else if operation == "Send" {
				MDMCommands = append(MDMCommands, priv)
			} else {
				nonCrudPrivileges = append(nonCrudPrivileges, priv)
			}
		} else {
			nonCrudPrivileges = append(nonCrudPrivileges, priv)
		}
	}

	var formattedPrivileges strings.Builder

	// Sort categories for consistent ordering
	sortedCategories := make([]string, 0, len(categories))
	for category := range categories {
		sortedCategories = append(sortedCategories, category)
	}
	sort.Strings(sortedCategories)

	for _, category := range sortedCategories {
		privileges := categories[category]
		// Adding a spacer with the category name
		formattedPrivileges.WriteString(fmt.Sprintf("---- Privilege Set: %s ----\n", category))
		formattedPrivileges.WriteString(fmt.Sprintf("    %s\n", strings.Join(privileges, "\n    ")))
		formattedPrivileges.WriteString("---- End ----\n\n")
	}

	if len(MDMCommands) > 0 {
		// Adding a spacer for Send MDM Commands
		formattedPrivileges.WriteString("---- MDM Commands ----\n")
		formattedPrivileges.WriteString(fmt.Sprintf("    %s\n", strings.Join(MDMCommands, "\n    ")))
		formattedPrivileges.WriteString("---- End ----\n\n")
	}

	if len(nonCrudPrivileges) > 0 {
		// Adding a spacer for non-CRUD privileges
		formattedPrivileges.WriteString("---- Other Jamf Pro Operations ----\n")
		formattedPrivileges.WriteString(fmt.Sprintf("    %s\n", strings.Join(nonCrudPrivileges, "\n    ")))
		formattedPrivileges.WriteString("---- End ----\n\n")
	}

	errs = append(errs, fmt.Errorf("%q contains an invalid privilege: %s; must be one of:\n%s", key, v, formattedPrivileges.String()))
	return
}
