name: Generate terraform docs
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4.1.1
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: examples/
          git-push: "true"
          output-format: markdown document
          output-file: USAGE.md
          output-method: replace
          args: --sensitive=false --hide requirements --required=false
          indention: 3
          config-file: .terraform-docs.yml
