name: golangci-lint
on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      REF_TO_CHECKOUT: ${{ github.event_name == 'pull_request' && format('refs/pull/{0}/head', github.event.pull_request.number) || github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.REF_TO_CHECKOUT }}
    
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1