name: Staticcheck lint
on:
  pull_request:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        #   v4.2.2   
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go
         #   v5.5.0
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: '1.24'

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: |
          staticcheck ./...
