name: PR Title Validation

on:
  pull_request:
  workflow_dispatch:
    inputs:
      pr_title:
        description: 'PR Title'
        required: true
        type: string

jobs:


  Check-PR-Title:
    env:
      PR_TITLE: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || inputs.pr_title }}

    runs-on: ubuntu-latest
    container: python:3.13-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Check Script
        run: python3 scripts/pr-title-validator.py



  