# Terraform Provider Registry release workflow.
name: Terraform Provider Release

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  # on pushes to either the specified branch or a version tag - see:
  # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags
  push:
    tags:
      - 'v*'
    branches:
      - main
      - release

jobs:
  # bump the version if not manually tagged
  version:
    id: version
    if: github.ref_type != 'tag'
    uses: mathieudutour/github-tag-action@v6.2
    permissions:
      contents: write  # Required push tags.
    with:
      create_annotated_tag: false
      default_bump: patch
      default_prerelease_bump: prepatch
      github_token: ${{ github.token }}
      pre_release_branches: main
      release_branches: release
      tag_prefix: v
      custom_release_rules: 'fix:patch,bug:patch,bugfix:patch,patch:patch,feat:patch,feat:minor:new resource,minor:minor,feat:major:breaking change,feat:major:API change,major:major'

  # Release for Partner and Community Providers
  terraform-provider-release:
    environment: 'terraform registry'
    name: 'Terraform Provider Release'
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v5.0.0
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'  # Your GPG private key
      gpg-private-key-passphrase: '${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}'  # Passphrase for your GPG key, if applicable
    with:
      release-notes: false # Set to true if you have release notes to include
      setup-go-version: '1.22' # Specify the Go version needed
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Release Notes
        run: sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/# $(git describe --abbrev=0 --exclude="$(git describe --abbrev=0 --match='v*.*.*' --tags)" --match='v*.*.*' --tags | tr -d v)/q;p" CHANGELOG.md > release-notes.txt
      - uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release-notes.txt
          retention-days: 1
