---
  # Terraform Provider testing workflow.
  name: Tests
  
  on:
    pull_request:
      branches:
        - main
      paths-ignore:
        - 'README.md'
    push:
      branches:
        - main
      paths-ignore:
        - 'README.md'
  
  # Testing only needs permissions to read the repository contents.
  permissions:
    contents: read
  
  jobs:
    test:
      name: Terraform Provider Acceptance Tests
      runs-on: ubuntu-latest
      timeout-minutes: 15
      strategy:
        fail-fast: false
        matrix:
          # list whatever Terraform versions here you would like to support
          terraform:
            - '1.9.*'
            # - '1.10.*'
            # - '1.11.*'
      steps:
        - name: Harden Runner
          uses: step-security/harden-runner@v2.11.1
          with:
            egress-policy: audit

        - name: Checkout repository
          uses: actions/checkout@v4.2.2
          with:
            fetch-depth: 0

        - name: Setup Go
          uses: actions/setup-go@v5.2.0
          with:
            go-version-file: 'go.mod'
            cache: true

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3.1.2
          with:
            terraform_version: ${{ matrix.terraform }}
            terraform_wrapper: false
            
        - run: go mod download
        - run: go build -v .
        - run: go generate ./...

        - name: git diff
          run: |
            git diff --compact-summary --exit-code || \
              (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3.1.2
          with:
            terraform_version: ${{ matrix.terraform }}
            terraform_wrapper: false

        - run: go mod download

        - name: Run Acceptance Tests
          env:
            TF_ACC: "1"
            JAMFPRO_TENANT_ID: ${{ secrets.JAMFPRO_TENANT_ID }}
            JAMFPRO_CLIENT_ID: ${{ secrets.JAMFPRO_CLIENT_ID }}
          run: go test -v -cover ./internal/
